export const users = [
  [
    {
      _id: '6574a0b60d3f07580fca4b15',
      index: 0,
      guid: '51e2b16f-fca9-4f38-b65f-a1b9f5acf6d8',
      isActive: false,
      balance: '$3,594.09',
      picture: 'http://placehold.it/32x32',
      age: 32,
      eyeColor: 'blue',
      name: 'Gamble Horne',
      gender: 'male',
      company: 'MARQET',
      email: 'gamblehorne@marqet.com',
      phone: '+1 (873) 418-3743',
      address: '609 Kenmore Terrace, Tioga, North Dakota, 3510',
      about:
        'Dolor reprehenderit non id incididunt laborum dolor irure velit. Minim laborum fugiat qui proident elit excepteur consectetur id adipisicing do irure. Sunt adipisicing sint culpa veniam ea adipisicing cillum enim esse nisi duis. Voluptate cupidatat excepteur dolore tempor exercitation duis. Incididunt fugiat sit irure fugiat in cupidatat. Eiusmod ut adipisicing aliquip id nostrud pariatur non consequat.\r\n',
      registered: '2014-03-29T11:19:31 -04:00',
      latitude: 54.158239,
      longitude: -53.205648,
      tags: [
        'exercitation',
        'anim',
        'eiusmod',
        'nostrud',
        'tempor',
        'incididunt',
        'nisi',
      ],
      friends: [
        {
          id: 0,
          name: 'Essie Howe',
        },
        {
          id: 1,
          name: 'Booth Walton',
        },
        {
          id: 2,
          name: 'Higgins Dickerson',
        },
      ],
      greeting: 'Hello, Gamble Horne! You have 10 unread messages.',
      favoriteFruit: 'strawberry',
    },
    {
      _id: '6574a0b6315a7dd464e7e907',
      index: 1,
      guid: '094dcbb0-0d4a-4540-af9b-9d017a2ee09d',
      isActive: false,
      balance: '$1,428.92',
      picture: 'http://placehold.it/32x32',
      age: 32,
      eyeColor: 'blue',
      name: 'Rosalyn Bullock',
      gender: 'female',
      company: 'NEOCENT',
      email: 'rosalynbullock@neocent.com',
      phone: '+1 (984) 504-3653',
      address: '425 Eaton Court, Thornport, Michigan, 272',
      about:
        'Officia qui voluptate proident nostrud aute in eiusmod officia velit. Nisi fugiat occaecat excepteur ex. Non anim cupidatat aute nostrud nulla anim irure dolore deserunt voluptate minim.\r\n',
      registered: '2018-09-24T12:59:11 -03:00',
      latitude: -54.797233,
      longitude: -151.252884,
      tags: ['amet', 'irure', 'nostrud', 'amet', 'ex', 'deserunt', 'magna'],
      friends: [
        {
          id: 0,
          name: 'Lorraine Riggs',
        },
        {
          id: 1,
          name: 'Bishop Wallace',
        },
        {
          id: 2,
          name: 'Anderson Alston',
        },
      ],
      greeting: 'Hello, Rosalyn Bullock! You have 4 unread messages.',
      favoriteFruit: 'apple',
    },
    {
      _id: '6574a0b6f6dbaf2bf0e39a34',
      index: 2,
      guid: '9ed9ed33-60c3-449a-a157-9ea2800e3d4a',
      isActive: true,
      balance: '$2,885.10',
      picture: 'http://placehold.it/32x32',
      age: 28,
      eyeColor: 'brown',
      name: 'Edwards Barton',
      gender: 'male',
      company: 'ZYTREK',
      email: 'edwardsbarton@zytrek.com',
      phone: '+1 (889) 552-2395',
      address: '631 Elmwood Avenue, Outlook, Puerto Rico, 7911',
      about:
        'Commodo duis minim consequat laborum. Exercitation ea minim nostrud cillum magna sit. Quis sunt qui ut proident laborum voluptate voluptate excepteur minim fugiat commodo ipsum.\r\n',
      registered: '2018-02-28T01:57:19 -03:00',
      latitude: -49.860296,
      longitude: 63.800354,
      tags: ['labore', 'cupidatat', 'deserunt', 'veniam', 'in', 'sunt', 'ut'],
      friends: [
        {
          id: 0,
          name: 'Stein Powell',
        },
        {
          id: 1,
          name: 'Berry Sanders',
        },
        {
          id: 2,
          name: 'Faulkner Aguirre',
        },
      ],
      greeting: 'Hello, Edwards Barton! You have 10 unread messages.',
      favoriteFruit: 'apple',
    },
    {
      _id: '6574a0b60dfae7e9a533f48c',
      index: 3,
      guid: 'f5a84a5c-ff71-409f-ab53-a57fbfc0fe82',
      isActive: true,
      balance: '$3,569.76',
      picture: 'http://placehold.it/32x32',
      age: 32,
      eyeColor: 'green',
      name: 'Mandy Cameron',
      gender: 'female',
      company: 'MAZUDA',
      email: 'mandycameron@mazuda.com',
      phone: '+1 (981) 583-3689',
      address: '373 Bush Street, Sunwest, Virgin Islands, 1132',
      about:
        'Tempor deserunt non nisi Lorem minim non eu esse eiusmod commodo eu officia sit. Fugiat ullamco nisi reprehenderit nulla esse ea ea in tempor elit laborum tempor tempor velit. Deserunt tempor aliqua eu duis ullamco amet tempor deserunt labore irure nulla. Anim labore ad nulla excepteur laboris quis anim id ipsum incididunt et exercitation do id. Id in mollit Lorem minim tempor excepteur pariatur et nisi deserunt excepteur et ea. Qui laborum non officia id quis pariatur nostrud aliquip.\r\n',
      registered: '2022-04-23T06:54:48 -03:00',
      latitude: 89.614924,
      longitude: -139.517562,
      tags: ['eiusmod', 'id', 'sunt', 'dolor', 'mollit', 'esse', 'officia'],
      friends: [
        {
          id: 0,
          name: 'Dickson Barron',
        },
        {
          id: 1,
          name: 'Stone Beach',
        },
        {
          id: 2,
          name: 'Boyle Vaughan',
        },
      ],
      greeting: 'Hello, Mandy Cameron! You have 1 unread messages.',
      favoriteFruit: 'apple',
    },
    {
      _id: '6574a0b663f5a359d870861f',
      index: 4,
      guid: '1ad707da-5a9b-4302-bb9a-2083d42a5e59',
      isActive: false,
      balance: '$3,398.84',
      picture: 'http://placehold.it/32x32',
      age: 24,
      eyeColor: 'brown',
      name: 'Jaime Rojas',
      gender: 'female',
      company: 'KINETICUT',
      email: 'jaimerojas@kineticut.com',
      phone: '+1 (817) 461-2301',
      address: '998 Pioneer Street, Fingerville, Guam, 8520',
      about:
        'Eiusmod consectetur est magna velit in velit culpa est culpa deserunt amet aliqua ad ut. Eu ex eu in nisi aliqua. Cupidatat cillum in proident est incididunt veniam sunt in commodo non. Nisi non deserunt cillum eiusmod. Cillum aliquip cillum aliqua ullamco laboris esse adipisicing commodo eiusmod magna. Irure exercitation duis elit sunt anim eiusmod irure deserunt sit. Ut dolor excepteur anim officia.\r\n',
      registered: '2020-05-27T10:45:54 -03:00',
      latitude: 50.078745,
      longitude: 135.087741,
      tags: ['qui', 'sunt', 'id', 'ex', 'mollit', 'labore', 'proident'],
      friends: [
        {
          id: 0,
          name: 'Cantrell Townsend',
        },
        {
          id: 1,
          name: 'Connie Curtis',
        },
        {
          id: 2,
          name: 'Melton Hester',
        },
      ],
      greeting: 'Hello, Jaime Rojas! You have 4 unread messages.',
      favoriteFruit: 'apple',
    },
  ],
];
